In [1]:
import numpy as np

In [2]:
# function to generate an array of random integers between 0 and 10, inclusive.
vector = np.random.randint(0, 11, size=5)

vector

array([ 1,  2, 10, 10,  4])

In [3]:
#function to create a vector with values ranging from 15 to 55.
vector = np.arange(15, 56)

vector[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [4]:
# Create a random array with 1000 elements
array = np.random.rand(1000)

In [5]:
# Compute the average, variance, and standard deviation
avg = np.mean(array)
var = np.var(array)
std = np.std(array)

In [10]:
"Average:", avg

('Average:', 0.4781821026412703)

In [7]:
"Variance:", var

('Variance:', 0.0817756083449679)

In [11]:
"Standard deviation:", std

('Standard deviation:', 0.2859643480313025)

In [13]:
# Create a 3x3 array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
# Calculate the cumulative sum along axis 1
cumsum_axis1 = np.cumsum(array, axis=1)

# Sum over rows for each of the 3 columns
sum_columns = np.sum(array, axis=0)

# Sum over columns for each of the 2 rows
sum_rows = np.sum(array, axis=1)


In [15]:
"Array:"
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
"Cumulative sum along axis 1:"
cumsum_axis1

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [17]:
"Sum over rows for each of the 3 columns:"
sum_columns

array([12, 15, 18])

In [18]:
"Sum over columns for each of the 2 rows:"
sum_rows

array([ 6, 15, 24])

In [19]:
# Define the two matrices as NumPy arrays
matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[1, 2], [3, 4]])

In [20]:
# Compute the multiplication of the two matrices
result = np.dot(matrix1, matrix2)

In [21]:
result

array([[1, 2],
       [3, 4]])